config/routes.rb
Rails.application.routes.draw do

  get 'facility_reservations/new'

  get 'facility_reservations/create'

  get 'facility_reservations/edit'

  get 'facility_reservations/update'

  get 'facility_reservations/destroy'

  get 'facility_reservations/index'

  get 'facility_reservations/show'

  get 'equipment_reservations/new'

  get 'equipment_reservations/create'

  get 'equipment_reservations/edit'

  get 'equipment_reservations/update'

  get 'equipment_reservations/destroy'

  get 'equipment_reservations/index'

  get 'equipment_reservations/show'

  get 'equipments/new'

  get 'equipments/create'

  get 'equipments/edit'

  get 'equipments/update'

  get 'equipments/destroy'

  get 'equipments/index'

  get 'equipments/show'

  get 'venues/new'

  get 'venues/create'

  get 'venues/edit'

  get 'venues/update'

  get 'venues/destroy'

  get 'venues/index'

  get 'venues/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages
  resources :reservations
  resources :readmissions
  resources :venues
  resources :equipments
  resources :facility_reservations
  resources :equipment_reservations
  
  root "pages#index"
  
  get 'pages/index'
  get '/admin' => 'users#new'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/studentlogin' => 'pages#student_login'
  get '/test' => 'reservations#test'

  

end

app/models/readmission.rb
class Readmission < ActiveRecord::Base
	belongs_to :resident
	belongs_to :room
end

app/controllers/readmissions_controller.rb
class ReadmissionsController < ApplicationController
	def new
		@readmission = Readmission.new
		@resident = Resident.new
		@room = Room.new
	end
	
	def create
		@readmission = Readmission.new(params[:id])
		@resient = Resident.new(params[:id_number])

		@readmission.save
		@resident.save

		if @readmission.save

			render :success
		else
			render :new
		end
	end

	def success
		@readmission = Readmission.find(:id)
	end
end

app/helpers/readmissions_helper.rb
module ReadmissionsHelper
end

app/views/readmissions/_form.html.erb
<%= simple_nested_form_for readmission do |f| %>
	<%= f.input :school_year %>
	<%= f.input :semester %>
	<%= f.fields_for :residents do |ff| %>
		<%= ff.input :id_number %>
		<%= ff.input :last_name %>
		<%= ff.input :first_name %>
		<%= ff.input :middle_initial %>
		<%= ff.input :mobile_number %>
		<%= ff.input :email %>
		<%= ff.input :year_level %>
		<%= ff.input :course %>
		<%= ff.input :dorm_scholar, as: :radio_buttons %>
	<% end %>
	<%= f.fields_for :rooms do |ff| %>
		<%= ff.input :building %>
		<%= ff.input :room_number %>
	<% end %>
	<%= f.input :check_in %>
	<%= f.submit "Save" %>
<% end %>

app/views/readmissions/index.html.erb
<h1>Pending Applications</h1>
<br>

<% @readmissions.each do |readmission| %>
	<%= readmission.id_number %> | 
	<%= link_to "Delete", readmission_path(readmission.id), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
<a href = "readmissions.csv"><button type = "button" class = "btn btn-default btn-xs"> Extract </button></a>

app/views/readmissions/new.html.erb
<h1>New Application</h1>
<hr>
<%= render partial: "readmissions/form", locals: { readmission: @readmission } %>

app/views/readmissions/success.html.erb
<h1> REGISTRATION SUCCES </h1>