config/routes.rb
Rails.application.routes.draw do

  get 'facility_reservations/new'

  get 'facility_reservations/create'

  get 'facility_reservations/edit'

  get 'facility_reservations/update'

  get 'facility_reservations/destroy'

  get 'facility_reservations/index'

  get 'facility_reservations/show'

  get 'equipment_reservations/new'

  get 'equipment_reservations/create'

  get 'equipment_reservations/edit'

  get 'equipment_reservations/update'

  get 'equipment_reservations/destroy'

  get 'equipment_reservations/index'

  get 'equipment_reservations/show'

  get 'equipments/new'

  get 'equipments/create'

  get 'equipments/edit'

  get 'equipments/update'

  get 'equipments/destroy'

  get 'equipments/index'

  get 'equipments/show'

  get 'venues/new'

  get 'venues/create'

  get 'venues/edit'

  get 'venues/update'

  get 'venues/destroy'

  get 'venues/index'

  get 'venues/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages
  resources :reservations
  resources :readmissions
  resources :venues
  resources :equipments
  resources :facility_reservations
  resources :equipment_reservations
  
  root "pages#index"
  
  get 'pages/index'
  get '/admin' => 'users#new'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/studentlogin' => 'pages#student_login'
  get '/test' => 'reservations#test'

  

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(reservation_params)

    if @venue.save
      render :index
    else
      render :new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    @venue.name = params[:venue][:name]
    @venue.description = params[:venue][:description]
    @venue.length = params[:venue][:length]
    @venue.width = params[:venue][:width]
    @venue.area = params[:venue][:area]

    if @reservation.save!
      render :success
    else
      render :edit
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to venues_path
  end

  def index
    @venues = Venue.all
  end

  def venue_params
    params.require(:venue).permit!
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= simple_form_for @venue do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :length %>
	<%= f.input :width %>
	<%= f.input :area %>
	<%= f.submit "Save" %>
<% end %>

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/edit.html.erb
<head>	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="home.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation" ><a href="pages">Home</a></li>
	  <li role="presentation"><a href="/about">About</a></li>
	  <li role="presentation"><a href="/contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="/admin">Admin</a></li>
	</ul>
  </div>
</nav>
Edit Venue
<%= simple_form_for venue do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :length %>
	<%= f.input :width %>
	<%= f.input :area %>
	<%= f.submit "Save" %>
<% end %>

app/views/venues/index.html.erb
<head>	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="home.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation" ><a href="pages#index">Home</a></li>
	  <li role="presentation"><a href="/about">About</a></li>
	  <li role="presentation"><a href="/contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="/admin">Admin</a></li>
	</ul>
  </div>
</nav>
<h1>List of Venues</h1>
<br>

<% @venues.each do |venue| %>
	Name: <%= venue.name %> <br />
	Description: <%= venue.description %> <br />
	Dimensions: <%= venue.length %> x <%= venue.width %>
	Area: <%= venue.area %> sq m
	<%= link_to "Edit", edit_venue_path(venue.id) %>
	<%= link_to "Delete", venue_path(venue.id), method: :delete, data: { confirm: "Are you sure?" } %>
	<br>
<% end %>
<a href = "venues.csv"><button type = "button" class = "btn btn-default btn-xs"> Extract </button></a>

app/views/venues/new.html.erb
<head>	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="home.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation" ><a href="/">Home</a></li>
	  <li role="presentation"><a href="/about">About</a></li>
	  <li role="presentation"><a href="/contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="/admin">Admin</a></li>
	</ul>
  </div>
</nav>
<h1>New Venue</h1>
<hr>
<%= render partial: "venues/form", locals: { venue: @venue } %>

app/views/venues/update.html.erb
<h1>Venues#update</h1>
<p>Find me in app/views/venues/update.html.erb</p>