config/routes.rb
Rails.application.routes.draw do

  get 'facility_reservations/new'

  get 'facility_reservations/create'

  get 'facility_reservations/edit'

  get 'facility_reservations/update'

  get 'facility_reservations/destroy'

  get 'facility_reservations/index'

  get 'facility_reservations/show'

  get 'equipment_reservations/new'

  get 'equipment_reservations/create'

  get 'equipment_reservations/edit'

  get 'equipment_reservations/update'

  get 'equipment_reservations/destroy'

  get 'equipment_reservations/index'

  get 'equipment_reservations/show'

  get 'equipments/new'

  get 'equipments/create'

  get 'equipments/edit'

  get 'equipments/update'

  get 'equipments/destroy'

  get 'equipments/index'

  get 'equipments/show'

  get 'venues/new'

  get 'venues/create'

  get 'venues/edit'

  get 'venues/update'

  get 'venues/destroy'

  get 'venues/index'

  get 'venues/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages
  resources :reservations
  resources :readmissions
  resources :venues
  resources :equipments
  resources :facility_reservations
  resources :equipment_reservations
  
  root "pages#index"
  
  get 'pages/index'
  get '/admin' => 'users#new'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/studentlogin' => 'pages#student_login'
  get '/test' => 'reservations#test'

  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates :school_year, presence: true, format: { with: /[2][0][0-9][0-9]-[2][0][0-9][0-9]/, message: "use right format: 20xx-20xx" }
	validates :last_name, presence: true
	validates :first_name, presence: true
	validates :middle_initial, presence: true, length: { maximum: 1 }, format: { with: /\A[a-zA-Z]+\z/ }
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "not valid email"}
	validates :mobile_number, presence: true, numericality: { only_integer: true }, length: {is:11}
	validates :id_number, presence: true, length: {is: 6}, numericality: { only_integer: true }, uniqueness: true
	validates :year_level, presence: true, length: {is: 1}
	validates :course, presence: true
	validates :building, presence: true
	validates :room_number, presence: true, length: {is: 3}, numericality: { only_integer: true }

	def self.as_csv
  		CSV.generate do |csv|
		    csv << column_names
		    all.each do |item|
		      csv << item.attributes.values_at(*column_names)
    		end
  		end
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
	end
	
	def create
		@reservation = Reservation.new(reservation_params)	
		@reservation.status = "Waitlisted"

		if @reservation.save
			ReservationMailer.confirmation_email(@reservation).deliver_now
			render :success
		else
			render :new
		end
	end

	def success
		@reservation = Reservation.find(:id)
	end

	def destroy
		@reservation = Reservation.find(params[:id])
		@reservation.destroy
		redirect_to reservations_path
	end

	def reservation_params
		params.require(:reservation).permit!
	end

	def index
	  @reservations = Reservation.order(:created_at)
	  
	  respond_to do |format|
	    format.html
	    format.csv { send_data @reservations.as_csv }
	  end
	end

	def edit
		@reservation = Reservation.find(params[:id])
	end

	def update
		@reservation = Reservation.find(params[:id])
		@reservation.school_year = params[:reservation][:school_year]
		@reservation.last_name = params[:reservation][:last_name]
		@reservation.first_name = params[:reservation][:first_name]
		@reservation.middle_initial = params[:reservation][:middle_initial]
		@reservation.mobile_number = params[:reservation][:mobile_number]
		@reservation.email = params[:reservation][:email]
		@reservation.id_number = params[:reservation][:id_number]
		@reservation.year_level = params[:reservation][:year_level]
		@reservation.course = params[:reservation][:course]
		@reservation.dorm_scholar = params[:reservation][:dorm_scholar]
		@reservation.building = params[:reservation][:building] 
		@reservation.room_number = params[:reservation][:room_number]
		@reservation.check_in = params[:reservation][:check_in]
	 	@reservation.status = params[:reservation][:status]

		if @reservation.save!
			ReservationMailer.confirmation_email(@reservation).deliver_now
			render :success
		else
			render :edit
		end
	end
end

app/views/reservations/_form.html.erb
<%= simple_form_for reservation do |f| %>
<div class = "row">
	<%= f.input :school_year %>
</div>
<div class = "row">
<div class = 'col-xs-5'>
	<%= f.input :last_name %>
	<%= f.input :first_name %>
	<%= f.input :middle_initial %>

</div>
<div class = 'col-xs-5'>
	<%= f.input :id_number %>
	<%= f.input :year_level %>
	<%= f.input :course %>
</div>
</div>
<div class = "row">
		<%= f.input :mobile_number %>
	<%= f.input :email %>
	<%= f.input :dorm_scholar, as: :radio_buttons %>
	<%= f.input :building, as: :select, collection: ["UD-N", "UD-S"] %>
	<%= f.input :room_number %>
	<%= f.input :check_in %>
	<%= f.submit "Save" %>
<% end %>
</div>

app/views/reservations/_reservation.erb
<h4><%= reservation.id_number  %></h4>
<div>
<b>Last Name:</b> <%= reservation.last_name %>
</div>
<div>
<b>First Name:</b> <%= reservation.first_name %>
</div>
<div>
<b>MI:</b> <%= reservation.middle_initial %>
</div>
<div>
<b>Building:</b> <%= reservation.building %>
</div>
<div>
<b>Room Number:</b> <%= reservation.room_number %>
</div>
<div>
<b>Check In Date:</b> <%= reservation.check_in %>
</div>
<div>
<b>Year Level: </b><%= reservation.year_level %>
</div>
<div>
<b>Course: </b><%= reservation.course %>
</div>

app/views/reservations/all.html.erb
<% @reservations.each do |reservation| %>
	<li><h2>	<%= link_to "#{reservation.name}", reservation_path(reservation.id) %></h2> </li>
<% end %>

app/views/reservations/edit.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation"><a href="/">Home</a></li>
	  <li role="presentation"><a href="about">About</a></li>
	  <li role="presentation" class="active"><a href="contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	<div class = "row">
		<h4 id="pgtitle">EDIT RESERVATION</h4>
	</div>
	<div class="row">

<%= simple_form_for @reservation do |f| %>
	<%= f.input :school_year %>
	<%= f.input :last_name %>
	<%= f.input :first_name %>
	<%= f.input :middle_initial %>
	<%= f.input :mobile_number %>
	<%= f.input :email %>
	<%= f.input :id_number %>
	<%= f.input :year_level %>
	<%= f.input :course %>
	<%= f.input :dorm_scholar, as: :radio_buttons %>
	<%= f.input :building, as: :select, collection: ["UD-N", "UD-S"] %>
	<%= f.input :room_number %>
	<%= f.input :check_in %>
	<%= f.input :status, as: :radio_buttons, collection: ["Accepted", "Rejected", "Waitlisted"] %>
	<%= f.submit "Save" %>
<% end %> 
	</div>
</div>

<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1 col-md-offset-2">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "./images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>
</body>

app/views/reservations/index.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation" ><a href="/">Home</a></li>
	  <li role="presentation"><a href="/about">About</a></li>
	  <li role="presentation"><a href="/contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	<div class = "row">
		<h4 id="pgtitle">PENDING RESERVATIONS</h4>
	</div>
	<div class="row">
		<% @reservations.each do |reservation| %>
	<%= reservation.id_number %>
	<%= reservation.last_name %>,
	<%= reservation.first_name %>
	<%= reservation.middle_initial %>.
	<%= reservation.year_level %>
	<%= reservation.course %>
	<%= reservation.status %>| 
	<%= link_to "Edit", edit_reservation_path(reservation.id) %>
	<%= link_to "Delete", reservation_path(reservation.id), method: :delete, data: { confirm: "Are you sure?" } %>
	<br>
<% end %>
<a href = "reservations.csv"><button type = "button" class = "btn btn-default btn-xs"> Extract </button></a>
	</div>
</div>

<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1 col-md-offset-2">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "./images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>
</body>

app/views/reservations/new.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="form.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation"><a href="/">Home</a></li>
	  <li role="presentation"><a href="about">About</a></li>
	  <li role="presentation"><a href="contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	<div class = "row">
		<h4 id="pgtitle">NEW RESERVATION</h4>
	</div>
	<div class="row">
		
<%= render partial: "reservations/form", locals: { reservation: @reservation } %>

	</div>
</div>
</body>
<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "/images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>

app/views/reservations/search.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link rel="stylesheet" type="text/css" href="home.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation" class="active"><a href="#">Home</a></li>
	  <li role="presentation"><a href="about">About</a></li>
	  <li role="presentation"><a href="contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	
	<div class = "row" id="centerpiece">
		<div id="imgcont" class = "col-xs-6">
			<img id="drmimg" src="./images/dorm.jpg" class="img-responsive" alt="dorm pic"> </img>
		</div>
		<div id="rtsd" class = "col-xs-6">
			<h5 id="san">SITE ANNOUNCEMENTS</h5>
			<div>
				<div id="sah" class = "col-xs-4">LOREM IPSUM</div><br>
				<p id="psa">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.  <a href="#" id="rdmr">  Read More</a></p>
			</div>
			<div>
				<div id="sah" class = "col-xs-4">LOREM IPSUM</div><br>
				<p id="psa">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.  <a href="#" id="rdmr">  Read More</a></p>
			</div>
	
		</div>
	</div>
</div>

<div id="boxes" class="container-fluid">
	<div class="row">
		<div class="row">
			<div class = "col-xs-1">
			</div>
			<div id="sectleft" class = "col-xs-5">
				<h4>FACILITIES</h4>
			</div>

			<div id="sectright" class = "col-xs-5">
				<h4>ADMISSION</h4>
			</div>
			<div class = "col-xs-1">
			</div>
		</div>
		<div class = "col-xs-1">
		</div>
		<div class = "col-xs-10">	
			<div class = "col-xs-3">
					<div id="sideimg" class = "col-xs-5">
						<img id="sdimg" src = "./images/Teaser1.png" class="img-responsive" alt = "sdimg">
					</div>
					<div id="reserve" class = "col-xs-7">
						<h5 id="rr">Reservations</h5>
						<button type="button" class="btn btn-default btn-xs">VENUE</button>
						</br>
						<button type="button" class="btn btn-default btn-xs">EQUIPMENT</button>
					</div>
			</div>
			<div class = "col-xs-3">
					<div id="sideimg" class = "col-xs-5">
						<img id="sdimg" src = "./images/Teaser1.png" class="img-responsive" alt = "sdimg">
					</div>
					<div id="view" class = "col-xs-7">
						<h5 id="rr">View<br>Gallery</h5>
						<p id="bxtxt">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</p>
					</div>
			</div>
			<div class = "col-xs-3">
					<div id="sideimg" class = "col-xs-5">
						<img id="sdimg" src = "./images/Teaser1.png" class="img-responsive" alt = "sdimg">
					</div>
					<div id="reserve" class = "col-xs-7">
						<h5 id="rr">Readmission</h5>
						<p id="bxtxt">Lorem ipsum dolor sit amet consectetur.</p>
						<a href="reservations/new"><button type="button" class="btn btn-default btn-xs">RESERVE ROOM</button></a>
					</div>
			</div>
			<div class = "col-xs-3">
					<div id="sideimg" class = "col-xs-5">
						<img id="sdimg" src = "./images/Teaser1.png" class="img-responsive" alt = "sdimg">
					</div>
					<a href="reservations/show">
					<div id="view" class = "col-xs-7">
						<h5 id="rr">View<br>Results</h5>
						<p id="bxtxt">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.</p>
					</div>
					</a>
			</div>
		</div>
		<div class = "col-xs-1">
		</div>
	</div>
</div>

<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1 col-md-offset-2">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "./images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>
</body>

app/views/reservations/show.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation"><a href="/">Home</a></li>
	  <li role="presentation"><a href="about">About</a></li>
	  <li role="presentation" class="active"><a href="contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	<div class = "row">
		<h4 id="pgtitle">FIND RESULTS</h4>
	</div>
	<div class="row">
		<%= simple_form_for @reservations do |f| %>
	<%= f.input :last_name %>
	<%= f.input :id_number %>
	<%= f.submit "Search" %>
<% end %> 
	</div>
</div>

<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1 col-md-offset-2">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "./images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>
</body>

app/views/reservations/success.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Ateneo Residence Halls Reservation System</title>
	<link href="/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="main.css">
	<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700|Montserrat' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two|Open+Sans:700,400' rel='stylesheet' type='text/css'>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
	<ul class="nav navbar-nav">
	  <li role="presentation"><a href="/">Home</a></li>
	  <li role="presentation"><a href="about">About</a></li>
	  <li role="presentation" class="active"><a href="contact">Contact Us</a></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
	  	<li id="right" role="presentation"><a href="admin">Admin</a></li>
	</ul>
  </div>
</nav>

<div id="bod" class = "container-fluid">
	<div class="row" id="title">
		<h1> ATENEO RESIDENCE HALLS </h1>
		<h3> RESERVATION SYSTEM </h3>
	</div>
	<div class = "row">
		<h4 id="pgtitle">READMISSION</h4>
	</div>
	<div class="row">
		<h1 id="uc">SUCCESS!</h1>
	</div>
</div>

<footer class="navbar navbar-fixed-bottom">
	<div class="row">
	  	<div class="col-md-8">
	  	<p>
			ATENEO DE MANILA UNIVERSITY. ALL RIGHTS RESERVED.
			<br>
			Katipunan Avenue Loyola Heights, Quezon City 1108, Philippines
			<br>
			426-6001 loc.5901-04 | ateneo.edu/univdorm
		</p>
		</div>
		<div class="col-md-1 col-md-offset-2">
		  	<p id="power">Powered by</p>
		  	<img id="wols" src = "./images/wols.png" class="img-responsive" alt = "wols">
		</div>
	</div>
</footer>
</body>

app/views/reservations/test.html.erb
<% @reservations.each do |reservation| %>
	<li><h2>	<%= link_to "#{reservation.name}", reservation_path(reservation.id) %></h2> </li>
<% end %>